var myImage1;
var myImage2;
var mySong;
var myAmplitude;
var myCanvas;
var fft;

function preload() {
  mySong = loadSound('./assets/allsheknows.mp3');
  myImage1 = loadImage('./assets/vinile2.png');
  myImage2 = loadImage("./assets/class.png");
}

function setup() {
  angleMode(DEGREES);
  myCanvas = createCanvas(windowWidth, windowHeight);
  myAmplitude = new p5.Amplitude(); //ampiezza

  mySong.pause();
  mySong.playMode('sustain'); //In 'sustain' mode, the sound will overlap with itself. In 'restart' mode it will stop and then start again.

  fft = new p5.FFT(); //FFT (Fast Fourier Transform): an algorithm that samples a signal over a period of time and divides it into its frequency components.
  mySong.connect(fft); // Connect soundfile to the fft
  mySong.rate(1);

  myCanvas.mouseClicked(function() {
    if (mySong.isPlaying() == false) {
      mySong.play();
      // mySong.loop();
    } else {
      mySong.pause();
    }
  });
}

function draw() {
  var myText1 = 'Do your ears a favor and listen to this.';
  var myText2 = 'Go ahead, click the vinyl...';

  push();
  fill('#d6d4cc');
  textFont('Oswald');
  textStyle(BOLD);
  noStroke();
  textSize(30);
  textAlign(CENTER);
  text(myText1, windowWidth / 2, windowHeight - 100);
  pop();

  push();
  fill('#d6d4cc');
  textFont('Oswald');
  textStyle(BOLD);
  noStroke();
  textSize(30);
  textAlign(CENTER);
  text(myText2, windowWidth / 2, windowHeight - 65);
  pop();

  background(51, 51, 51, 42);

  push();
  translate((width / 2) + 110, height / 2);
  rotate(frameCount); //vinyl speed

  //visuals generated by the amplitude of the song
  var level = myAmplitude.getLevel();
  var rhythm = map(level, 0, 1, 0, windowWidth / 60);
  var waveform = fft.waveform(); //fft applied to the waveform
  noFill();
  stroke('#d6d4cc');
  strokeWeight(rhythm);

  //rotation
  for (var i = 0; i < 80; i++) {
    var y = map(waveform[i], -1, 1, 0, width * 6 / 7); // to interpolate values between a min and max
    point(width / 6, y);
    rotate(8);
  }

  image(myImage1, -windowWidth / 8, -windowWidth / 8, windowWidth / 4, windowWidth / 4);
  pop();

  push();
  imageMode(CENTER);
  image(myImage2, (width / 2) - 60, height / 2, windowWidth / 4, windowWidth / 4);
  pop();
}

//to restart the song
function keyPressed() {
  mySong.playMode('restart');
  mySong.play();
}

function windowResized() {
  resizeCanvas(windowWidth, windowWidth);
}

//music credits: The LaFontaines - All She Knows (free download)
